'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
# Limit up to a certain integer but not including that integer
def even_fib(m):
    a = 0
    b = 1
    fib = [0, 1]
    for x in range(50):
        fib.append(fib[a] + fib[b])
        a+=1
        b+=1


    final = 0
    for i in range(0, len(fib)):
        if fib[i] < m and fib[i] % 2 == 0:
            final += fib[i]
        
    return final

'''
Example results:-

eve_fib(0) -> 0
eve_fib(33) -> 10
eve_fib(25997544) -> 19544084

'''
